name: Bug
description: BBBug!
assignees:
  - abiriadev
labels:
  - Bug
title: kimo
body:
  - type: markdown
    attributes:
      value: Thanks for taking your time to report the bug!
  - type: checkboxes
    attributes:
      label: Have you searched for existing issues?
      description: Please ensure your issue hasn't been reported yet.
      options:
        - label: I've checked for existing issues
          required: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: What exactly happened?
      description: |
        Provide a detailed description of the issue.

        - If multiple indipendant bugs occurred simultaneously, please report each issue separately.
  - type: textarea
    attributes:
      label: Errors or log messages
      description: |
        Copy and paste any relevant error messages, log output, or other pertinent information.

        Don't forget to use code blocks(\`\`\`) for better readablity.
  - type: textarea
    attributes:
      label: Can you provide a screenshot?
      description: If possible, include a screenshot illustrating the issue.
  - type: textarea
    attributes:
      label: What was the expected behavior?
      description: |
        Describe the expected outcome or just your suggestion.

        - You can skip this if it's obvious that the issue is a bug.
  - type: textarea
    attributes:
      label: How can we reproduce the issue?
      description: |
        Provide detailed steps or a reproducible scenario to help us understand and replicate the problem.
  - type: input
    attributes:
      label: Which version of Seia are you using?
      description: |
        type

        ```sh
        seia --version
        ```

        in your terminal.
  - type: input
    attributes:
      label: Which package manager and version are you using?
      description: |
        Note: Some issues may arise with Yarn Berry.
  - type: textarea
    attributes:
      label: (optional) additional information about your environment.
      description: |
        Tell me more about your environment if you use very uncommon environment, or the bug occure in very specific contexts.

        Like your operating system, browser, docker, etc.
