name: Bug
description: BBBug!
assignees:
  - abiriadev
labels:
  - Bug
title: kimo
body:
  - type: markdown
    attributes:
      value: Thanks for taking your time to report the bug!
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Have you searched for existing issues?
        
        Please ensure your issue hasn't been reported yet.
      options:
        - label: I've checked for existing issues
          required: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug describtion
      description: |
        What exactly happened? Please provide a detailed description of the issue.

        _If multiple indipendant bugs occurred simultaneously, please report each issue separately._
      value: |
        <!--
        Describe the bug you encoutered.

        Use screenshot or GIF if possible, which are intuitive way to convey something.
        -->
        
        <!--
        ```ts
        Copy and paste any relevant error messages, log output, or other pertinent information.

        Use multiple codeblocks for multiple messages.
        ```
        -->
  - type: textarea
    attributes:
      label: Expected behaivor
      description: |
        What was the expected behavior? Describe the expected outcome or just your suggestion.

        _You can skip this if it's obvious that the issue is a bug._
  - type: markdown
    attributes:
      value: |
        ## Steps to reproduce
  - type: input
    attributes:
      label: Version information
      description: |
        Which version of Seia are you using? type the below command in your terminal.

        ```sh
        seia --version
        ```
    validations:
      required: true
  - type: input
    attributes:
      label: Package manager
      description: |
        Which package manager and version are you using?
        
        Type the below command in your terminal.

        ```sh
        npm -v
        yarn -v
        pnpm -v
        ```

        Have you tested with other package manager? Is this package manager specific issue?
        _Note: Some issues only arise with Yarn Berry._
  - type: textarea
    attributes:
      label: Reproduction steps
      description: |
        How can we reproduce the issue?
        
        Provide detailed steps or a reproducible scenario to help us understand and replicate the problem.

        If you have reproduction repository, please provide its link.
